#!/bin/bash

# 默认设置：默认为 Headless 模式 (1)
IS_HEADLESS=1
MODEL="gz_x500"

# 检查参数
if [ -n "$1" ]; then
    IS_HEADLESS=0 # 有参数则需要 GUI (关闭 Headless)
    case "$1" in
        2)
            MODEL="gz_quadtailsitter"
            ;;
        *)
            MODEL="gz_x500" 
            ;;
    esac
fi

# --- 执行 ---
echo "🚀 Starting MicroXRCEAgent on port 8888..."
MicroXRCEAgent udp4 -p 8888 & 

if [ "$IS_HEADLESS" -eq 1 ]; then
    echo "🚁 Starting PX4 SITL ($MODEL) -- Mode: Headless"
    HEADLESS=1 make px4_sitl $MODEL
else
    echo "🚁 Starting PX4 SITL ($MODEL) -- Mode: GUI"
    make px4_sitl $MODEL
fi
